# Generated by Django 3.0 on 2019-12-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceApp', '0010_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
